# Generated by Django 4.2.3 on 2023-07-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
